# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e907306bcd68590d5ce2e602b7b213184b51c16c055ff5d3511b77efe842ab33dc7b07e29949be506d41c06b6542cb19b9b857ee6bccff1b07ba46aaced4cd9

test:
  secret_key_base: 8aea53b3ee9439363c94c8f447f6843c85845fc3cbbf48a6b2add5d3b0b170bf212fc871bf0c8c7a27801aa929cedabe61091cdcf47bc743e7902923277a9c83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
